[GENERAL]
Title = "a title"

[[FEEDS]]
Name = "Nick name for feed"
Number = "item number"
URL = "feed url string"
feed_last_read_iso = "iso time"
feed_last_read_unix = "unixtime"
feed_previous_last_read_iso = "iso time"
feed_previous_last_read_unix = "unixtime"
newest_feed_item_unix = "unixtime"
newest_feed_item_iso = "iso time"
oldest_feed_item_iso = "iso time"
oldest_feed_item_unix = "unixtime"

[BSKY_INFO]
previous_last_posted_unix = "unixtime"
previous_last_posted_iso = "iso time"
last_posted_unix = "unixtime"
last_posted_iso = "iso time"

