[GENERAL]
statefile = "salt-state.toml"
timezone_abbreviation = "UTC"
number_of_feeds_monitoring = 2

[[FEEDS]]
Name = "Erik at Artsocial.boston"
Number = 1
URL = "https://artsocial.boston/@erik.rss"
type = "rss"

[[FEEDS]]
Name = "Erik at Puget.social"
Number = 2
URL = "https://puget.social/@erik.rss"
type = "rss"

[BSKY_ACCOUNT]
handle = "pinky"
app_passwd = "spit"
